# Generated by Django 6.0.6 on 2026-07-07 08:07

from django.db import migrations


ROLES = [
    ("admin", "Full system access — manage all resources and users."),
    ("owner", "Game owner — full CRUD on own games through developer/publisher membership."),
    ("developer", "Game developer — create games, manage own game listings."),
    ("end_user", "End user — browse catalog, suggest tags, rate and review."),
]


def seed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    for name, description in ROLES:
        Role.objects.get_or_create(name=name, defaults={"description": description})


def remove_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(name__in=[r[0] for r in ROLES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_roles, remove_roles),
    ]

