# Generated by Django 6.0.6 on 2026-07-07 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='games.developer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'developer')},
            },
        ),
        migrations.CreateModel(
            name='PublisherMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='games.publisher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'publisher')},
            },
        ),
    ]
